<a href="https://colab.research.google.com/github/stevenmkaraszewski-collab/DataAnalytics/blob/main/Steven_Karaszewski_Python_Analysis_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
!pip install pandas
!pip install matplotlib

import pandas as pd
import matplotlib.pyplot as plt

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [52]:
df=pd.read_csv('https://raw.githubusercontent.com/stevenmkaraszewski-collab/DataAnalytics/refs/heads/main/311_Service_Requests_from_2019May.csv',low_memory=False)

In [53]:
#4. Find the total number of rows and columns and their data types

rows, columns = df.shape
print(f"The total number of rows is {rows}")
print(f"The total number of columns is {columns}")
print("Data types of columns:")
print(df.dtypes)

The total number of rows is 69637
The total number of columns is 21
Data types of columns:
Unique Key                  int64
Created Date               object
Closed Date                object
Agency                     object
Complaint Type             object
Location Type              object
Incident Zip               object
Incident Address           object
Street Name                object
Address Type               object
City                       object
Landmark                   object
Facility Type              object
Status                     object
Due Date                   object
Resolution Description     object
BBL                       float64
Borough                    object
Latitude                  float64
Longitude                 float64
Location                   object
dtype: object

In [54]:
#5. Find the summary statistics for the file

df.describe()

         Unique Key           BBL      Latitude     Longitude
count  6.963700e+04  5.570200e+04  65634.000000  65634.000000
mean   4.260307e+07  2.869652e+09     40.723149    -73.924517
std    5.269818e+04  1.184250e+09      0.083621      0.085089
min    4.251278e+07  0.000000e+00     40.500025    -74.252279
25%    4.258004e+07  2.030690e+09     40.664461    -73.972161
50%    4.260019e+07  3.034830e+09     40.716443    -73.929758
75%    4.262095e+07  4.023330e+09     40.780783    -73.874064
max    4.297343e+07  5.080480e+09     40.912869    -73.700597

In [55]:
#6. Analyze the data and find how many missing values are in the dataset

df.isna().sum()

Unique Key                    0
Created Date                  0
Closed Date                5011
Agency                        0
Complaint Type                0
Location Type             15659
Incident Zip               2248
Incident Address          10604
Street Name               10605
Address Type               1330
City                       2221
Landmark                  69621
Facility Type             45556
Status                        0
Due Date                  36798
Resolution Description     6058
BBL                       13935
Borough                       0
Latitude                   4003
Longitude                  4003
Location                   4003
dtype: int64

In [56]:
#7. Find missing values in all columns

df.isna()

,Unique Key,Created Date,Closed Date,Agency,Complaint Type,Location Type,Incident Zip,Incident Address,Street Name,Address Type,...,Landmark,Facility Type,Status,Due Date,Resolution Description,BBL,Borough,Latitude,Longitude,Location
0,False,False,False,False,False,True,False,False,False,False,...,True,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69632,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
69633,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
69634,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
69635,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
69636,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False

In [57]:
#8. Use imputation techniques( mean, median etc.) to clean the data

In [58]:
df['Complaint Type'].value_counts()

Complaint Type
Noise - Residential                    5838
Request Large Bulky Item Collection    5301
Illegal Parking                        5257
Blocked Driveway                       3391
Street Condition                       3080
                                       ...
Highway Sign - Damaged                    1
Taxi Compliment                           1
Illegal Fireworks                         1
Mosquitoes                                1
Advocate-Co-opCondo Abatement             1
Name: count, Length: 186, dtype: int64